package_dir: "/package"
steps:
- emerge --root /package {{.Values.atom}}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"

excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
