package_dir: "/package"

prelude:
- |
  [ -e "package.use/{{.Values.category}}-{{.Values.name}}.use" ] && \
  cp -rf package.use/{{.Values.category}}-{{.Values.name}} /etc/portage/package.use/{{.Values.category}}-{{.Values.name}}.use
- |
  [ -e "package.accept_keywords/{{.Values.category}}-{{.Values.name}}.accept_keywords" ] && \
  cp -rf package.accept_keywords/{{.Values.category}}-{{.Values.name}}.accept_keywords /etc/portage/package.accept_keywords/{{.Values.category}}-{{.Values.name}}.accept_keywords

steps:
{{ if .Values.pre_emerge }}
- emerge -1 -j ${JOBS} {{.Values.pre_emerge}}
{{end}}
- emerge -j ${JOBS} --root /package {{.Values.atom}}

requires: {{.Values.build_requires | toYaml | nindent 1}}

env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}

excludes:
{{ template "portage_excludes" }}
