{{ define "build" }}

env:
{{ if .Values.labels }}
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
{{ else }}
- JOBS=3
{{ end }}
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"

requires:
{{ range .Values.build_requires }}
- category: {{ .category }}
  name: {{ .name }}
  version: ">=0"
{{ end }}

{{ if .Values.requires_final_images }}
requires_final_images: {{ .Values.requires_final_images }}
{{ end }}

{{ if .Values.unpack }}
unpack: {{ .Values.unpack }}
{{ end }}

prelude:
{{ $packages := include "cr.packages" .Values }}
{{ if $packages }}
{{ range $packages | splitList " " }}
{{ $package := . | replace "layerbase-" "layers-" | replace "\"" "" }}
- |
  set -x; \
  if [ -e "package.accept_keywords/{{ $package }}.accept_keywords" ]; then \
    cp -rf package.accept_keywords/{{ $package }}.accept_keywords /etc/portage/package.accept_keywords/{{ $package }}.accept_keywords; \
  fi; \
  if [ -e "package.license/{{ $package }}.license" ]; then \
    cp -rf package.license/{{ $package }}.license /etc/portage/package.license/{{ $package }}.license; \
  fi; \
  if [ -e "package.use/{{ $package }}.use" ]; then \
    cp -rf package.use/{{ $package }}.use /etc/portage/package.use/{{ $package }}.use; \
  fi;
{{ end }}
{{ end }}

{{ range include "cr.prereqs" .Values | fromJsonArray }}
- {{ . }}
{{ end }}

steps:

{{ if .Values.preemerge }}
{{ range .Values.preemerge }}
{{ $tokens := . | splitList ";" }}
{{ if eq (len $tokens) 1 }}
- emerge -1 -j ${JOBS} {{ index $tokens 0 }}
{{ else if eq (len $tokens) 2 }}
- {{ index $tokens 1 }} emerge -1 -j ${JOBS} {{ index $tokens 0 }}
{{ end }}
{{ end }}
{{ end }}

{{ if .Values.atoms }}
{{ $tokens := .Values.atoms | splitList ";" }}
{{ if eq (len $tokens) 1 }}
- emerge -1 -j ${JOBS} {{ index $tokens 0 }}
{{ else if eq (len $tokens) 2 }}
- {{ index $tokens 1 }} emerge -1 -j ${JOBS} {{ index $tokens 0 }}
{{ end }}
{{ end }}

{{ if .Values.unmerge }}
{{ range .Values.unmerge }}
- emerge -C {{ . }}
{{ end }}
{{ end }}
{{ if .Values.etc_update }}
{{ if .Values.etc_update.mode }}
- etc-update -q --automode {{ .Values.etc_update.mode }}
{{ end }}
{{ end }}

{{ if ne .Values.category "buildbase" }}
excludes:
- ^/etc/csh.env
- ^/etc/environment.d/10-gentoo-env.conf
- ^/etc/ld.so.conf
- ^/etc/profile.env
- ^/luetbuild
- ^/usr/portage
- ^/usr/portage/distfiles
- ^/usr/share/applications/mimeinfo.cache
- ^/var/cache/edb
- ^/var/cache/distfiles
- ^/var/cache/fontconfig
{{ if ne .Values.category "layerbase" }}
- ^/var/db/pkg
{{ end }}
- ^/var/db/repos
- ^/var/lib/portage
- ^/var/log
# devel split
# - ^/usr/include
# - ^/luetbuild
# - ^/tmp
{{ end }}

{{ if eq .Values.category "layerbase" }}
subpackages:
  - category: "layers"
    name: "{{ .Values.name }}"
    version: "{{ .Values.version }}"
    excludes:
    - ^/var
    hidden: false
{{ end }}

#     includes:
#     - ^/var/db/pkg/.*
#     excludes:
#     - ^/var$
#     - ^/var/db$

{{ end }}
