prelude:
- bash prelude.sh
{{ if .Values.overlay }}
- USE="-subversion -mercurial" emerge app-portage/layman
- layman -L
- echo "y" | layman -a {{.Values.overlay}}
{{end}}
{{ if .Values.pre_emerge }}
- emerge -1 -j ${JOBS} {{.Values.pre_emerge}}
{{end}}

steps:
{{ if .Values.emerge_env_overrides }}
- {{.Values.emerge_env_overrides}} emerge -j ${JOBS} {{.Values.atom}}
{{else}}
- emerge -j ${JOBS} {{.Values.atom}}
{{end}}

requires: {{.Values.build_requires | toYaml | nindent 1}}

env:
{{ if .Values.labels }}
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
{{else}}
- JOBS=3
{{end}}
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"

excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
- ^/usr/share/applications/mimeinfo.cache
- ^/etc/ld.so.conf
- ^/etc/csh.env
- ^/etc/environment.d/10-gentoo-env.conf
- ^/etc/profile.env
