name: Build Set

on:
  workflow_call:
    inputs:
      build-sets:
        type: string
        required: true
        description: 'Stringified JSON object listing target build sets'
      set-id:
        type: string
        required: true
        description: 'Target build set id'
    secrets:
      QUAY_ROBOT_USERNAME:
        required: true
      QUAY_ROBOT_PASSWORD:
        required: true

jobs:
  build:
    if: ${{ fromJson(inputs.build-sets)[inputs.set-id] }}
    strategy:
      matrix:
        include: ${{ fromJson(inputs.build-sets)[inputs.set-id] }}
    outputs:
      matrix-sets: ${{ inputs.build-sets }}
    env:
      FINAL_REPO: quay.io/mocaccino/mocaccino-community
      CURRENT_PACKAGE:  ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
      PULL_REPOSITORY: quay.io/mocaccino/desktop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release space from worker
      run: |
        echo "Listing top largest packages"
        dpkg-query -Wf '${Package}\t\t${Installed-Size}\n' | sort -n | tail -n 100
        df -h
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove --auto-remove android-sdk-platform-tools
        sudo apt-get purge --auto-remove android-sdk-platform-tools
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo apt-get remove -y '^dotnet-.*'
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        sudo apt-get remove -y '^ghc-.*'
        sudo apt-get remove -y '.*jdk.*'
        sudo apt-get remove -y '.*jre.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
    - run: |
        git fetch --prune --unshallow
    - name: Login to Quay Registry
      run: echo ${{ secrets.QUAY_ROBOT_PASSWORD }} | docker login -u ${{ secrets.QUAY_ROBOT_USERNAME }} --password-stdin quay.io

    - name: Install deps 🔧
      run: |
        curl https://luet.io/install.sh | sudo sh
    - name: Install Go
      uses: actions/setup-go@v2
      with:
          go-version: '^1.16'
    - name: Build packages 🔧
      run: |
        sudo luet install -y repository/mocaccino-desktop-stable
        export PATH=$PATH:/usr/local/go/bin
        mkdir build || true
        pushd ./.github
        go build -o build
        popd
        sudo -E ./.github/build
        ls -liah $PWD/build
        sudo chmod -R 777 $PWD/build
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.category }}-${{ matrix.name }}-${{ matrix.version }}.zip
        path: |
          build/
