name: Build

on:
  push:
    branches: [ main ]

jobs:

  generate-matrix-sets:
    name: Generate matrix sets for build
    runs-on: ubuntu-latest
    outputs:
      matrix-sets: ${{ steps.set-matrix-sets.outputs.matrix-sets }}
      matrix-set-ids: ${{ steps.set-matrix-set-ids.outputs.matrix-set-ids }}
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
          sudo luet install utils/jq
      - name: Set matrix sets for build
        id: set-matrix-sets
        run: echo "::set-output name=matrix-sets::$(luet tree pkglist --tree packages -o json | jq -rc '[.packages | _nwise(16)]')"
      - name: Set matrix ids for build
        id: set-matrix-set-ids
        run: echo "::set-output name=matrix-set-ids::$(echo $MATRIX_SETS | jq -rc 'to_entries | map(.key)')"
        env:
          MATRIX_SETS: ${{ steps.set-matrix-sets.outputs.matrix-sets }}

  generate-matrix:
    name: build set ${{ matrix.set-id }}
    needs: generate-matrix-sets
    strategy:
      matrix: 
        set-id: ${{ fromJson(needs.generate-matrix-sets.outputs.matrix-set-ids) }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set matrix for build
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(echo $MATRIX | jq -rc '.[${{ matrix.set-id }}]')"
        env:
          MATRIX: ${{ needs.generate-matrix-sets.outputs.matrix-sets }}

  build:
    needs: generate-matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    env:
      FINAL_REPO: quay.io/mocaccino/mocaccino-community
      CURRENT_PACKAGE:  ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
      PULL_REPOSITORY: quay.io/mocaccino/desktop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release space from worker
      run: |
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
    - run: |
        git fetch --prune --unshallow
    - name: Login to Quay Registry
      run: echo ${{ secrets.QUAY_ROBOT_PASSWORD }} | docker login -u ${{ secrets.QUAY_ROBOT_USERNAME }} --password-stdin quay.io

    - name: Install deps 🔧
      run: |
        curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
    - name: Install Go
      uses: actions/setup-go@v2
      with:
          go-version: '^1.16'
    - name: Build packages 🔧
      run: |
        sudo luet install -y repository/mocaccino-desktop-stable
        export PATH=$PATH:/usr/local/go/bin
        mkdir build || true
        pushd ./.github
        go build -o build
        popd
        sudo -E ./.github/build
        ls -liah $PWD/build
        sudo chmod -R 777 $PWD/build
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.category }}-${{ matrix.name }}-${{ matrix.version }}.zip
        path: |
          build/

  
