name: Cleanup runner

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */2 * *'
jobs:
  clean:
    runs-on: [self-hosted, x64]
    steps:
      - name: Cleanup
        run: |
                sudo docker system prune --force --volumes --all
